# 6. summarize params into dataframe from returned list in step 5.

#' comet_list_to_df
#'
#' @param results_list result list generated by loop_data
#' @param method method used to fit the model
#'
#' @return summary dataframe one row per sample
#' @export
#'
#' @examples
#' in_data <- data.frame(Sample = c("001","002","003"),
#' c_0 = c(40,50,60), c_15=c(25,27,30), c_30=c(20,21,22), c_60=c(15,17,18), c_120=c(12,11,10))
#' sample_list <- loop_comet_data(in_data, "nls")
#' sample_dat <- comet_list_to_df(sample_list, "nls")
#'
comet_list_to_df <- function(results_list, method) {
  # Initialize an empty dataframe to store the results
  if (method == "nls") {
    list_dat <- data.frame(Sample = character(),
                           Coef_F = numeric(),
                           Coef_S = numeric(),
                           Coef_k_f = numeric(),
                           Coef_k_s = numeric(),
                           R_squared = numeric(),
                           RSE = numeric(),
                           Half_life_overall = numeric(),
                           Half_life_fast = numeric(),
                           Half_life_slow = numeric(),
                           stringsAsFactors = FALSE)
  } else if (method == "brms") {
    list_dat <- data.frame(Sample = character(),
                           Coef_F = numeric(),
                           Coef_S = numeric(),
                           Coef_k_f = numeric(),
                           Coef_k_s = numeric(),
                           LOOIC = numeric(),
                           Half_life_overall = numeric(),
                           Half_life_fast = numeric(),
                           Half_life_slow = numeric(),
                           stringsAsFactors = FALSE)
  } else {
    stop("Invalid method argument. Method must be either 'nls' or 'brms'.")
  }

  # Iterate over each element in results_list
  for (sample_name in names(results_list)) {
    sample_results <- results_list[[sample_name]]  # Extract results for the current sample

    # Create a row for the current sample and append it to the list_dat dataframe
    if (method == "nls") {
      list_dat <- rbind(list_dat, data.frame(Sample = sample_name,
                                             Coef_F = sample_results$params[1],
                                             Coef_S = sample_results$params[2],
                                             Coef_k_f = sample_results$params[3],
                                             Coef_k_s = sample_results$params[4],
                                             R_squared = sample_results$R_squared,
                                             RSE = sample_results$RSE,
                                             Half_life_overall = sample_results$half_life$overall,
                                             Half_life_fast = sample_results$half_life$fast_phase,
                                             Half_life_slow = sample_results$half_life$slow_phase,
                                             stringsAsFactors = FALSE))
    } else if (method == "brms") {
      list_dat <- rbind(list_dat, data.frame(Sample = sample_name,
                                             Coef_F = sample_results$params[1],
                                             Coef_S = sample_results$params[2],
                                             Coef_k_f = sample_results$params[3],
                                             Coef_k_s = sample_results$params[4],
                                             LOOIC = sample_results$loo$estimates["looic","Estimate"],
                                             Half_life_overall = sample_results$half_life$overall,
                                             Half_life_fast = sample_results$half_life$fast_phase,
                                             Half_life_slow = sample_results$half_life$slow_phase,
                                             stringsAsFactors = FALSE))
    }
  }

  # Return the dataframe
  return(list_dat)
}
